### ISSUE TITLE
.eslintrc 업데이트

### ISSUE THREAD

**Issue by namenu** [ridi/Reader.js#4]
https://github.com/ridibooks/style-guide/blob/master/JavaScript/.eslintrc

ESLint 설정은 이 파일에 있는 내용으로 업데이트 부탁합니다.
룰셋 변경에는 언제나 열려있습니다, 대응이 어렵거나 불합리한 규칙이라고 생각한다면 알려주세요.

**Comment by DavinAhn** [comment]
@namenu 
comma-dangle이 off가 아니라 warn이어야 할 이유가 있나요?
warn일 때 너무 많은 경고를 보게되어 중요한 것을 보지 못하게 될 것 같아요

**Comment by namenu** [comment]
@DaVinAhn 
원래 기준은 error 이지만, 당장 빌드가 안되는 프로젝트가 많은 상황을 고려하여 warn으로 하였습니다. (추후에는 error로 강제할 예정입니다.)

off 가 아닌 이유는 리뷰의 중요성이 매우 커졌기 때문이고, 따라서 diff 를 간결하게 만드는 것이 더 중요해졌기 때문입니다.

당장 경고가 너무 많아 문제가 된다면, 해당 규칙을 off 로 override 하되 없애는 issue 도 등록을 해주시면 되겠습니다!

**Comment by DavinAhn** [comment]
@namenu 
아, 그러면 나중에는 줄 마지막 ',' 생략은 오류로 보게 되는 거군요?

**Comment by namenu** [comment]
@DaVinAhn 네 그렇습니다!
